# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Caravans of Gold'
description:      'The Block Museum at Northwestern University presents the first major exhibition on the scope of medieval Saharan trade from the eighth to sixteenth centuries.'
url:              ''
baseurl:          ''
copyright:        'Created by Kathleen Berzock, Sarah Estrela, Chris Diaz, and the students of ART HIST 395: Museums Seminar, Northwestern University, Spring 2019'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
  - LICENSE
  - LICENSE.txt
  - convert.sh
  - convert-jpeg.sh
  - wax_theme.gemspec
  - s3_website.yml
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  fragments: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'fragment' # the layout for the pages to use
    metadata:
      source: 'fragments_20191007.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/caravans' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      fragments:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - artist_maker
          - section
          - _date
          - object_type
          - region_culture_time_period
          - credit_line
          - description
          - thumb_150

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'About'
    link: '/about/'
  - label: 'Tour'
    link: '/tour/'
  - label: 'Collection'
    link: '/collection/'
  - label: 'Search'
    link: '/search/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  logos:
    - img: 'https://www.blockmuseum.northwestern.edu/css/images/block-logo.svg'
      link: 'https://www.blockmuseum.northwestern.edu'
      alt: 'Northwestern Block Museum of Art'
    - img: '/img/libraries_logo.jpg'
      link: 'https://www.library.northwestern.edu/'
      alt: 'Northwestern Libraries'

root: '/'     
# FIN
